apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-initializer-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
